
export interface BrainTeaser {
  question: string;
  answer: string;
}

export const BRAIN_TEASERS: BrainTeaser[] = [
  { question: "I have cities, but no houses. I have mountains, but no trees. I have water, but no fish. What am I?", answer: "A map" },
  { question: "What has to be broken before you can use it?", answer: "An egg" },
  { question: "What is full of holes but still holds water?", answer: "A sponge" },
  { question: "What question can you never answer yes to?", answer: "Are you asleep yet?" },
  { question: "What is always in front of you but can’t be seen?", answer: "The future" },
  { question: "What has a neck without a head, and a body without legs?", answer: "A bottle" },
  { question: "What can you catch, but not throw?", answer: "A cold" },
  { question: "What goes up but never comes down?", answer: "Your age" },
  { question: "A man who was outside in the rain without an umbrella or hat didn’t get a single hair on his head wet. Why?", answer: "He was bald." },
  { question: "What gets wet while drying?", answer: "A towel" },
  { question: "I am an odd number. Take away a letter and I become even. What number am I?", answer: "Seven" },
  { question: "If you drop me I’m sure to crack, but give me a smile and I’ll always smile back. What am I?", answer: "A mirror" },
  { question: "What building has the most stories?", answer: "A library" },
  { question: "What has one eye, but can’t see?", answer: "A needle" },
  { question: "What has many keys but can't open a single lock?", answer: "A piano" },
  { question: "What has words but never speaks?", answer: "A book" },
  { question: "The more you take, the more you leave behind. What are they?", answer: "Footsteps" },
  { question: "What can travel around the world while staying in a corner?", answer: "A stamp" },
  { question: "What begins with T, ends with T, and has T in it?", answer: "A teapot" },
  { question: "What has hands but can’t clap?", answer: "A clock" },
  { question: "What has a heart that doesn’t beat?", answer: "An artichoke" },
  { question: "What gets sharper the more you use it?", answer: "Your brain" },
  { question: "I’m tall when I’m young, and short when I’m old. What am I?", answer: "A candle" },
  { question: "What belongs to you but is used more by others?", answer: "Your name" },
  { question: "What kind of tree can you carry in your hand?", answer: "A palm tree" },
  { question: "What can you hold without ever touching?", answer: "A conversation" },
{ question: "What has ears but cannot hear?", answer: "A cornfield" },
{ question: "What runs but never walks?", answer: "A river" },
{ question: "What can fill a room but takes up no space?", answer: "Light" },
{ question: "What has a thumb and four fingers but isn’t alive?", answer: "A glove" },
{ question: "What has a head and a tail, but no body?", answer: "A coin" },
{ question: "What invention lets you see through walls?", answer: "A window" },
{ question: "What can be cracked, made, told, and played?", answer: "A joke" },
{ question: "What has an end but no beginning?", answer: "A stick" },
{ question: "What flies without wings and cries without eyes?", answer: "A cloud" },
{ question: "What has a ring but no finger?", answer: "A telephone" },
{ question: "What teaches without speaking?", answer: "Experience" },
{ question: "What has legs but can’t walk?", answer: "A table" },
{ question: "What comes down but never goes up?", answer: "Rain" },
{ question: "What can you break just by saying it?", answer: "A promise" },
{ question: "What begins with an E but only contains one letter?", answer: "An envelope" },
{ question: "What moves faster: heat or cold?", answer: "Heat—because you can catch a cold" },
{ question: "What is the hardest thing to hold?", answer: "Your breath" },
{ question: "What has 13 hearts but no other organs?", answer: "A deck of cards" },
{ question: "What comes once in a minute, twice in a moment, but never in a thousand years?", answer: "The letter M" },
{ question: "What can you keep after giving it to someone?", answer: "Your word" },
{ question: "What room has no doors or windows?", answer: "A mushroom" },
{ question: "What building has the coldest stories?", answer: "An ice library (pun!)" },
{ question: "What’s easy to get into but hard to get out of?", answer: "Trouble" },
{ question: "What gets bigger the more you take away?", answer: "A hole" },
{ question: "What kind of band never plays music?", answer: "A rubber band" },
{ question: "What has roots but no soil?", answer: "A math root" },
{ question: "What can you write with but cannot see?", answer: "Your imagination" },
{ question: "What grows when you feed it but dies when you water it?", answer: "A fire" },
{ question: "What has a bed but never sleeps?", answer: "A riverbed" },
{ question: "What has teeth but cannot bite?", answer: "A comb" },
{ question: "What loses its head in the morning but gets it back at night?", answer: "A pillow" },
{ question: "What has stripes but no clothing?", answer: "A zebra" },
{ question: "What kind of coat is always wet?", answer: "A coat of paint" },
{ question: "What can be measured but not seen?", answer: "Time" },
{ question: "What animal turns into a house?", answer: "A turtle" },
{ question: "What has wings but cannot fly?", answer: "A stadium (wings of seating)" },
{ question: "What makes more the more you share it?", answer: "Happiness" },
{ question: "What can you hear but never see?", answer: "Sound" },
{ question: "Where does today come before yesterday?", answer: "In the dictionary" },
{ question: "What has pages but isn’t a book?", answer: "A calendar" },
{ question: "What begins with P and ends with E and has thousands of letters?", answer: "The post office" },
{ question: "What kind of key opens no doors?", answer: "A monkey" },
{ question: "What can you always count on even when you're wrong?", answer: "Your fingers" },
{ question: "What has a spine but no bones?", answer: "A book" },
{ question: "What has a beginning but no end?", answer: "A circle" },
{ question: "What kind of math makes you warm?", answer: "A blanket (because it has many layers!)" },
{ question: "What has a bark but no bite?", answer: "A tree" },
{ question: "What type of music do planets listen to?", answer: "Neptunes" },
{ question: "What kind of cup can’t hold water?", answer: "A hiccup" },
{ question: "What goes through cities and fields but never moves?", answer: "A road" },
{ question: "What can you open without touching?", answer: "Your mind" },
{ question: "What has four wheels and flies?", answer: "A garbage truck" },
{ question: "What can cross water without getting wet?", answer: "A shadow" },
{ question: "What turns everything around but never moves?", answer: "A mirror" },
{ question: "What can you only use once you give it away?", answer: "Advice" },
{ question: "What gets lighter the darker it gets?", answer: "A flame" },
{ question: "What sleeps in the day and works at night without being alive?", answer: "A streetlight" },
{ question: "What comes at the end of everything?", answer: "The letter G" },
{ question: "What rises but never stops rising?", answer: "Knowledge" },
{ question: "What grows when you share it and shrinks when you hide it?", answer: "Courage" },
{ question: "What has lines but isn’t a book?", answer: "Notebook paper" },
{ question: "What is easier to pick up the bigger it gets?", answer: "A conversation" },
{ question: "What kind of ship has two mates but no captain?", answer: "A relationship" },
{ question: "What comes in pieces but becomes whole when shared?", answer: "A puzzle" },
{ question: "What can you learn from but never talk to?", answer: "History" },
{ question: "What can be cracked but stays whole?", answer: "A riddle" },
{ question: "What requires training but has no muscles?", answer: "Your mind" },
{ question: "What shines brightest when the world is darkest?", answer: "Hope" },
{ question: "What helps you see but has no eyes?", answer: "A telescope" },
{ question: "What needs answers but doesn’t ask questions?", answer: "A test" },
{ question: "What has circles but never spins?", answer: "A bullseye" },
{ question: "What is shaped by pressure but admired for strength?", answer: "A diamond" },
{ question: "What moves without touching and speaks without talking?", answer: "The wind" },
{ question: "What stays in one corner yet covers the world?", answer: "The internet" },
{ question: "What grows roots but never touches dirt?", answer: "Knowledge roots" },
{ question: "What is powerful but weighs nothing?", answer: "An idea" },
{ question: "What can disappear the moment you say its name?", answer: "Silence" },
{ question: "What has letters but no words?", answer: "Alphabet soup" },
{ question: "What do you throw out when you want to use it and take in when you don't?", answer: "An anchor" },
{ question: "What has light but cannot see?", answer: "A lamp" },
{ question: "What spreads quickly but is invisible?", answer: "A rumor" },
{ question: "What is the one thing you lose the moment you try to hold on to it?", answer: "Time" },
{ question: "What has no legs but can run long distances?", answer: "A rumor" },
{ question: "What wins every race without moving?", answer: "Time" },
{ question: "What is stronger than steel but invisible?", answer: "Determination" }
];
