export interface Quote {
  text: string;
  author: string | null;
}

export const QUOTES: Quote[] = [
  { text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
  { text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle" },
  { text: "The only thing we have to fear is fear itself.", author: "Franklin D. Roosevelt" },
  { text: "Do not go where the path may lead, go instead where there is no path and leave a trail.", author: "Ralph Waldo Emerson" },
  { text: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
  { text: "Life is what happens when you're busy making other plans.", author: "John Lennon" },
  { text: "Get busy living or get busy dying.", author: "Stephen King" },
  { text: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
  { text: "Many of life's failures are people who did not realize how close they were to success when they gave up.", author: "Thomas A. Edison" },
  { text: "If you want to live a happy life, tie it to a goal, not to people or things.", author: "Albert Einstein" },
  { text: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth" },
  { text: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
  { text: "The whole secret of a successful life is to find out what is one’s destiny to do, and then do it.", author: "Henry Ford" },
  { text: "The unexamined life is not worth living.", author: "Socrates" },
  { text: "Turn your wounds into wisdom.", author: "Oprah Winfrey" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "Don't cry because it's over, smile because it happened.", author: "Dr. Seuss" },
  { text: "Everything you can imagine is real.", author: "Pablo Picasso" },
  { text: "The best way to predict the future is to invent it.", author: "Alan Kay" },
  { text: "Learn something new every day.", author: "Unknown" },
  { text: "Dream big. Work hard. Stay humble.", author: "Unknown" },
  { text: "Mistakes are proof you’re trying.", author: "Jennifer Lim" },
  { text: "Education is the key to unlock your future.", author: "Unknown" },
  { text: "The expert in anything was once a beginner.", author: "Helen Hayes" },
  { text: "Don’t just go to school, learn to grow.", author: "Unknown" },
  { text: "Believe you can, and you’re halfway there.", author: "Theodore Roosevelt" },
  { text: "Work hard in silence. Let success make the noise.", author: "Frank Ocean" },
  { text: "Every accomplishment starts with the decision to try.", author: "John F. Kennedy" },
  { text: "The more you learn, the more you earn.", author: "Warren Buffett" },
  { text: "Be a student of life, not just school.", author: "Unknown" },
  { text: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "Learning never stops.", author: "Unknown" },
  { text: "You don’t have to be perfect to be amazing.", author: "Unknown" },
  { text: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
  { text: "Read more, learn more, grow more.", author: "Unknown" },
  { text: "Small steps every day lead to big results.", author: "Unknown" },
  { text: "Don’t be afraid to ask questions.", author: "Unknown" },
  { text: "Smart is something you become, not something you are.", author: "Unknown" },
  { text: "Learning is a journey, not a race.", author: "Unknown" },
  { text: "Your education is your superpower.", author: "Unknown" },
  { text: "Try again. Fail again. Fail better.", author: "Samuel Beckett" },
  { text: "Never stop being curious.", author: "Unknown" },
  { text: "Be proud of how far you’ve come.", author: "Unknown" },
  { text: "Every day is a chance to learn something new.", author: "Unknown" },
  { text: "Your future is created by what you do today.", author: "Unknown" },
  { text: "Don’t limit your challenges. Challenge your limits.", author: "Unknown" },
  { text: "Education is your ticket to freedom.", author: "Oprah Winfrey" },
  { text: "Be the reason someone learns something new today.", author: "Unknown" },
  { text: "Strive for progress, not perfection.", author: "Unknown" },
  { text: "You don’t need to be the best, just better than yesterday.", author: "Unknown" },
  { text: "Learning is a treasure that follows its owner everywhere.", author: "Chinese Proverb" },
  { text: "Success doesn’t come from what you do occasionally, but what you do consistently.", author: "Unknown" },
  { text: "Think positive, study hard, and make it happen.", author: "Unknown" },
  { text: "Be curious. Be creative. Be kind.", author: "Unknown" },
  { text: "A little progress each day adds up to big results.", author: "Unknown" },
  { text: "You learn more from failure than from success.", author: "Unknown" },
  { text: "Learn from yesterday, live for today, hope for tomorrow.", author: "Albert Einstein" },
  { text: "Your attitude determines your direction.", author: "Unknown" },
  { text: "Learning is your passport to the future.", author: "Unknown" },
  { text: "You are capable of amazing things.", author: "Unknown" },
  { text: "Don’t compare your chapter one to someone else’s chapter ten.", author: "Unknown" },
  { text: "Education opens doors you didn’t even know existed.", author: "Unknown" },
  { text: "Doubt kills more dreams than failure ever will.", author: "Suzy Kassem" },
  { text: "Keep learning. Keep growing. Keep shining.", author: "Unknown" },
  { text: "Focus on learning, not just grades.", author: "Unknown" },
  { text: "Your mindset is the key to your success.", author: "Unknown" },
  { text: "Learn to listen before you speak.", author: "Unknown" },
  { text: "The more you practice, the better you get.", author: "Unknown" },
  { text: "Never let the fear of failing stop you from learning.", author: "Unknown" },
  { text: "Ask, learn, improve, repeat.", author: "Unknown" },
  { text: "Curiosity is the first step to wisdom.", author: "Unknown" },
  { text: "Keep your eyes on the stars and your feet on the ground.", author: "Theodore Roosevelt" },
  { text: "Knowledge is power. Use it wisely.", author: "Unknown" },
  { text: "Be brave enough to start.", author: "Unknown" },
  { text: "Every great learner was once a beginner.", author: "Unknown" },
  { text: "Don’t be afraid to learn something difficult.", author: "Unknown" },
  { text: "Success starts with self-belief.", author: "Unknown" },
  { text: "Learning is like climbing a mountain. Enjoy the view.", author: "Unknown" },
  { text: "Stay curious, stay learning, stay growing.", author: "Unknown" },
  { text: "Don’t give up. Great things take time.", author: "Unknown" },
  { text: "Study smart, not just hard.", author: "Unknown" },
  { text: "Your effort today builds your tomorrow.", author: "Unknown" },
  { text: "Keep asking questions. That’s how you learn.", author: "Unknown" },
  { text: "You are your best investment.", author: "Unknown" },
  { text: "One book, one pen, one student can change the world.", author: "Malala Yousafzai" },
  { text: "Learn something that makes you better than you were yesterday.", author: "Unknown" },
  { text: "Dream, learn, achieve.", author: "Unknown" },
  { text: "Study now, shine later.", author: "Unknown" },
  { text: "What you learn today builds your future tomorrow.", author: "Unknown" },
  { text: "Keep learning, because life never stops teaching.", author: "Unknown" },
  { text: "Stay hungry for knowledge.", author: "Steve Jobs" },
  { text: "Make today a learning day.", author: "Unknown" },
  { text: "The best project you’ll ever work on is yourself.", author: "Unknown" },
  { text: "Every question is a doorway to discovery.", author: "Unknown" },
  { text: "Dream it. Learn it. Do it.", author: "Unknown" },
  { text: "Be kind. Be curious. Be unstoppable.", author: "Unknown" },
  { text: "There’s no limit to what you can learn.", author: "Unknown" },
  { text: "Stay focused, stay curious, stay kind.", author: "Unknown" },
  { text: "Learning is your adventure—enjoy the ride.", author: "Unknown" },
  { text: "Curiosity turns ordinary into extraordinary.", author: "Unknown" },
  { text: "Never stop improving yourself.", author: "Unknown" },
  { text: "Ask questions. Seek answers. Keep growing.", author: "Unknown" }
  { text: "Success is the sum of small efforts repeated day after day.", author: "Robert Collier" },
{ text: "The beautiful thing about learning is nobody can take it away from you.", author: "B.B. King" },
{ text: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
{ text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
{ text: "Act as if what you do makes a difference. It does.", author: "William James" },
{ text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis" },
{ text: "Hard work beats talent when talent doesn’t work hard.", author: "Tim Notke" },
{ text: "Champions keep playing until they get it right.", author: "Billie Jean King" },
{ text: "Learning is the only thing the mind never exhausts or fears.", author: "Leonardo da Vinci" },
{ text: "Don’t wait for opportunity. Create it.", author: "Unknown" },
{ text: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
{ text: "The journey of a thousand miles begins with a single step.", author: "Lao Tzu" },
{ text: "Education is the passport to the future, for tomorrow belongs to those who prepare for it today.", author: "Malcolm X" },
{ text: "Success isn’t how far you got, but the distance you traveled from where you started.", author: "Steve Prefontaine" },
{ text: "The man who moves a mountain begins by carrying away small stones.", author: "Confucius" },
{ text: "What you do today can improve all your tomorrows.", author: "Ralph Marston" },
{ text: "Learn as if you will live forever, live like you will die tomorrow.", author: "Mahatma Gandhi" },
{ text: "Don’t be pushed by your problems; be led by your dreams.", author: "Ralph Waldo Emerson" },
{ text: "Success is not final; failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
{ text: "Your life is your story. Write well. Edit often.", author: "Susan Statham" },
{ text: "You are what you do, not what you say you’ll do.", author: "Carl Jung" },
{ text: "The expert in anything was once a learner who didn’t quit.", author: "Unknown" },
{ text: "Doing your best means never stopping to try.", author: "Benjamin Franklin" },
{ text: "To learn a new language is to gain a new soul.", author: "Hungarian Proverb" },
{ text: "Knowledge will bring you the opportunity to make a difference.", author: "Claire Fagin" },
{ text: "Don’t count the days. Make the days count.", author: "Muhammad Ali" },
{ text: "The mind is not a vessel to be filled, but a fire to be kindled.", author: "Plutarch" },
{ text: "Great things never come from comfort zones.", author: "Unknown" },
{ text: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
{ text: "If you can dream it, you can do it.", author: "Walt Disney" },
{ text: "Everyone you admire was once a beginner.", author: "Unknown" },
{ text: "Don’t let what you can’t do stop you from doing what you can do.", author: "John Wooden" },
{ text: "Imagination is more important than knowledge.", author: "Albert Einstein" },
{ text: "Your potential is endless.", author: "Unknown" },
{ text: "Learn from everyone. Follow no one. Be yourself.", author: "Unknown" },
{ text: "Your dreams don’t work unless you do.", author: "John C. Maxwell" },
{ text: "With self-discipline, all things are possible.", author: "Theodore Roosevelt" },
{ text: "Every great mind was once a student asking questions.", author: "Unknown" },
{ text: "Failure is simply the opportunity to begin again, this time more intelligently.", author: "Henry Ford" },
{ text: "The best view comes after the hardest climb.", author: "Unknown" },
{ text: "Difficult roads often lead to beautiful destinations.", author: "Unknown" },
{ text: "Be the energy you want to attract.", author: "Unknown" },
{ text: "Learning is growing, and growing means changing.", author: "Unknown" },
{ text: "A book is a dream you can hold in your hands.", author: "Neil Gaiman" },
{ text: "Focus on the step in front of you, not the whole staircase.", author: "Unknown" },
{ text: "Success is a journey, not a destination.", author: "Arthur Ashe" },
{ text: "Courage begins with showing up.", author: "Brené Brown" },
{ text: "Nothing worth having comes easy.", author: "Theodore Roosevelt" },
{ text: "Small acts of learning create big results over time.", author: "Unknown" },
{ text: "Today a reader, tomorrow a leader.", author: "Margaret Fuller" },
{ text: "Positive thoughts lead to positive results.", author: "Unknown" },
{ text: "Don’t quit. Suffer now and live the rest of your life as a champion.", author: "Muhammad Ali" },
{ text: "The best way to learn is to do.", author: "Paul Halmos" },
{ text: "Learning is a treasure no one can steal.", author: "Chinese Proverb" },
{ text: "You grow through what you go through.", author: "Unknown" },
{ text: "Work until your idols become your rivals.", author: "Unknown" },
{ text: "Every student can learn, just not on the same day or in the same way.", author: "George Evans" },
{ text: "Great achievements begin with great questions.", author: "Unknown" },
{ text: "Don’t be afraid to be a beginner.", author: "Unknown" },
{ text: "Your brain is a muscle—exercise it daily.", author: "Unknown" },
{ text: "Be bold enough to use your voice, brave enough to listen, and smart enough to learn.", author: "Unknown" },
{ text: "The more you know, the more powerful you become.", author: "Unknown" },
{ text: "If you stumble, make it part of the dance.", author: "Unknown" },
{ text: "Today is another chance to get better.", author: "Unknown" },
{ text: "Reading gives you someplace to go when you have to stay where you are.", author: "Mason Cooley" },
{ text: "You don’t drown by falling in the water; you drown by staying there.", author: "Edwin Louis Cole" },
{ text: "Be a voice, not an echo.", author: "Albert Einstein" },
{ text: "Strength grows in the moments you think you can’t go on but keep going anyway.", author: "Unknown" },
{ text: "Practice makes progress.", author: "Unknown" },
{ text: "Be the student who never stops trying.", author: "Unknown" },
{ text: "Let your curiosity lead the way.", author: "Unknown" },
{ text: "Make your education a priority; your future self will thank you.", author: "Unknown" },
{ text: "Never stop chasing improvement.", author: "Unknown" },
{ text: "Every day is a fresh start.", author: "Unknown" },
{ text: "Where you are is not who you are.", author: "Unknown" },
{ text: "Success is built on the courage to try.", author: "Unknown" },
{ text: "Learning fuels confidence.", author: "Unknown" },
{ text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi" },
{ text: "A curious mind will always find answers.", author: "Unknown" },
{ text: "Your habits decide your future.", author: "Unknown" },
{ text: "In learning you will teach, and in teaching you will learn.", author: "Phil Collins" },
{ text: "Great learners ask great questions.", author: "Unknown" },
{ text: "Don’t fear mistakes; they’re proof you’re growing.", author: "Unknown" },
{ text: "Dreams don’t work unless you do the learning behind them.", author: "Unknown" },
{ text: "The harder the battle, the sweeter the victory.", author: "Les Brown" },
{ text: "Be curious about the world, and the world becomes your classroom.", author: "Unknown" },
{ text: "Learning is planting seeds for the future.", author: "Unknown" },
{ text: "Your only limit is your mind.", author: "Unknown" },
{ text: "Focus on progress, not perfection.", author: "Unknown" },
{ text: "A good education is the foundation for a better future.", author: "Elizabeth Warren" },
{ text: "Believe in the power of yet: I don’t understand… yet.", author: "Carol Dweck" },
{ text: "Open books, open minds.", author: "Unknown" },
{ text: "You become what you repeatedly do.", author: "Aristotle" },
{ text: "Your learning can change your life. Let it.", author: "Unknown" },
{ text: "The world rewards those who keep learning.", author: "Unknown" },
{ text: "Stay curious—questions are the seeds of discovery.", author: "Unknown" },
{ text: "Keep moving forward, even if it’s slow.", author: "Unknown" },
{ text: "Every day is a new chance to become smarter, stronger, and kinder.", author: "Unknown" }
];
